course_name = "大学物理"
repo_type = "normal"
course_code = "PHYS1001"

description = """
**注意！从 2024 春季学期开始，《大学物理》课程安排有所调整，但仅更改了某些模块的讲授顺序，总体内容不变，因此将原「大学物理 IA」、「大学物理 IB」栏目合并为「大学物理」栏目。**

鉴于部分资料中仍有「大学物理 IA」、「大学物理 IB」和「大学物理 II」等字样，为了避免新旧课程混淆，下面列出新旧课程对照表。**大家对照下表查找资料。** 例如，原先《大学物理 IB》的笔记里，有关「振动与波动」的部分，就可供《大学物理 XA》的同学所用。

| 课程名称 | 开课学期 | 学分 | 主要内容 |
| :--- | :--- | :--- | :--- |
| **原**大学物理 IA | 大一春 | 4.0 | 运动与力、狭义相对论、电磁学 |
| **原**大学物理 IB | 大二秋 | 4.0 | 振动与波动、光学、热学、量子物理 |
| **原**大学物理 II | 大一春 | 4.0 | 运动与力、狭义相对论、电磁学、振动与波动、光学 |
| **新**大学物理 XA | 大一春 | 5.0 | 运动与力、振动与波动、狭义相对论、电磁学 |
| **新**大学物理 XB | 大二秋 | 4.0 | 光学、热学、量子物理 |
| **新**大学物理 IA | 大一春 | 4.5 | 运动与力、振动与波动、电磁学 |
| **新**大学物理 IB | 大二秋 | 4.5 | 光学、热学、狭义相对论、量子物理 |
"""

[[lecturers]]
name = "马永辉"

[[lecturers.reviews]]
content = """
  授课风格：PPT，偶尔板书。
  2023 年期末考试前公布了班上学生的平时成绩，除了个别不交作业的，大多数人都是 29 或 30 分。
  2024 以及 2025 都公布了平时成绩，24 春共三次考勤，每次一分，25 秋考勤未计入平时分数。
  个人认为马老师的 PPT 是所有老师里最适合自学以及速通的，所以无论你是想在学期中稳扎稳打学习，还是在学期末两周速通，马老师都是非常适合选择的老师。
"""
author = { name = "", link = "", date = "" }

[[lecturers]]
name = "林国平"

[[lecturers.reviews]]
content = """
  用 PPT，几乎不用板书。上课几乎是照着 PPT 念的，而且语调没有太大的起伏，很容易昏昏欲睡。
  PPT 做的很细致，而且乐于回答学生问题（实际上他的水平很高）。鉴于 23 级开始和本部联考，他的消息是最灵通的，他的班级是最早了解本部相关消息的。
  不用听课，直接看他的 PPT 即可。习题课可以听一听，课后有问题直接找他询问即可。
"""
author = { name = "", link = "", date = "" }

[[lecturers]]
name = "王永杰"

[[lecturers.reviews]]
content = """
  用 PPT，很少板书。
  2024 秋没有上课考勤过，仅最后两节习题课考勤。
  PPT 念得比较细致，解释得其实也很清楚。但是因为语调没有什么变化所以听起来比较容易犯困。
"""
author = { name = "", link = "", date = "" }

[[lecturers]]
name = "孙华锐"

[[lecturers.reviews]]
content = """
  原《大学物理 II》授课教师。
  老师教学态度严谨、讲课条理清晰，平易近人，风格幽默风趣，疫情上网课期间，下课后老师会继续待在课堂给同学们答疑解惑，平时也会在 QQ 上给同学们解答问题，总之是一位非常认真负责的老师。
  PPT 中的知识点十分简洁凝练，层层深入，而且上面有许多例题辅助知识点的理解和应用，课程以知识点教学及例题讲解为主。
"""
author = { name = "", link = "", date = "" }

[[lecturers]]
name = "阮琦锋"

[[lecturers.reviews]]
content = """
  为《大学物理 XA》授课教师，24 级没有继续教授《大学物理 XB》。
  老师人非常好，教学细致清晰，课上有很多例题辅助理解，课后也非常愿意给大家答疑。
  不定期考勤，若缺勤会适当扣平时分。但考勤未到或者平时分未满的同学可以通过课上回答问题的方式加回平时分，最后期末多数人平时分也都是 29、30 分。
"""
author = { name = "", link = "", date = "" }

[[lecturers]]
name = "王斌"

[[lecturers.reviews]]
content = """
  据说是咱们学校物理老师不够，从深大请来的，所以在某些方面（深大按gpa计算的，所以90分以上都是4.0，老师在扣分方面会严格一些）可能和泥深情况不太一样，上课水平还行
  24级大学物理XB的授课老师 平时分为四次作业加一次小测 缺少一次作业或者一次小测，平时分直接-5分，对比其他老师平时分几乎给满的操作，我只能说，像大物这种课还是得抢，所以万一你上了他的课，可能平时对自己的要求要严一点！
"""
author = { name = "DUCKSEEDYHB", link = "https://duckseedyhb.github.io/", date = "2026-02" }

[[textbooks]]
title = "物理学 上册"
book_author = "东南大学等七所工科院校编，马文蔚、周雨青、解希顺等改编"
publisher = "高等教育出版社"
edition = "第 7 版"
type = "textbook"

[[textbooks]]
title = "物理学 下册"
book_author = "东南大学等七所工科院校编，马文蔚、周雨青、解希顺等改编"
publisher = "高等教育出版社"
edition = "第 7 版"
type = "textbook"

[[textbooks]]
title = "大学物理学 上册"
book_author = "王少杰，顾牧，王祖源编"
publisher = "高等教育出版社"
edition = "第 5 版"
type = "textbook"

[[textbooks]]
title = "大学物理学 下册"
book_author = "王少杰，顾牧，王祖源编"
publisher = "高等教育出版社"
edition = "第 5 版"
type = "textbook"

[[online_resources]]
title = "黎光旭说物理 - 大物 XA 课程合集"
url = "https://www.bilibili.com/video/BV1n741117gN"
description = "专攻马文蔚大学物理，覆盖运动学、动力学、振动与波、相对论、电磁场。上课前会复习旧知识，对新知识有概览、有详细推导；讲解形象，覆盖初学盲点。"

[[online_resources]]
title = "黎光旭说物理 - 大物 XB 课程合集"
url = "https://www.bilibili.com/video/BV18H4y197Pa"
description = "覆盖光学、气体动理论及热力学。注：合集没有量子物理、光学-偏振部分。"

[[online_resources]]
title = "大学物理马文蔚版-东北大学"
url = "https://www.bilibili.com/video/BV1Aj411878M/"
description = "东北大学的力学、电磁学、热学和光学都不错，教材版本一致。"

[[online_resources]]
title = "大学物理马文蔚版-东南大学"
url = "https://www.bilibili.com/video/BV1kW411P7VY/"
description = "可以补充东北大学网课中讲的不太好的振动与波动、相对论、量子物理部分。"

[[online_resources]]
title = "卡西欧 FX-991CNX 计算器使用指南"
url = "https://hoa.moe/blog/how-to-use-fx991cn/"
description = "学长制作的计算器使用指南，建议熟练掌握。"

[[online_resources]]
title = "科学常数的使用方法"
url = "https://www.zhihu.com/question/381394202/answer/1721124149"
description = "包含科学常数的调用方法、名称以及单位。"

[[exam]]
content = """
**从 2024 年春季开始，深圳校区的大学物理与本部联考。** 2024 年和本部联考后，大物考试难度大幅上升，平均分保守估计降低了 15 分左右。

2024 春季学期大物 XA 期末试卷结构为 10 题选择 + 10 题填空 + 6 题大题。
2024 秋季学期大物 XB 期末试卷结构为 10 题填空 + 1 题推导证明 + 7 题计算 + 1 题设计与应用。

2024 秋大物 XB 考试考到了很多很偏的知识点，卷子大背诵且和物理思维毫无关系。本部期中考全是热学，且本部没有学习几何光学内容，导致上课花了大量时间的热学只考了 2 题填空题和 1 题推导证明题，量子物理和波动光学考了很多，而几何光学一题不考。

考试均允许带计算器。
"""

[[exam]]
content = """
2025 年春季学期开始（2024 级），为和本部统一，增加了期中考试，占总评成绩的 20%。
试卷结构为 9 道填空题 + 3 道计算题。期中考试考过的内容在期末考试会减少占比，但不代表没有。
"""

[[advice]]
content = """
大物虽然在和本部联考后大改，但是总体上还是大背诵，两学期大物要对物理学的各个领域都有一个入门级的学习，自然有很多公式定义定理要记忆。

大物 XA 中力学和电磁学思维量较大，力学需要正确进行受力分析，电磁场需要正确找到各个电磁量和力学量的关系，在高中基础上引入了微积分，这也是大物 XA 的难点所在。

大物 XB 思维量则小得多，一个直观感受是没有积分计算，只有简单的加减乘除，但是大物 XB 内容较散，光学、热学、量子物理各部分各成体系，并无很强的相关性。并且由于振动与波动、狭义相对论部分内容移至大物 XA 部分教学，本部加入了大量的原本不要求的内容和拓展应用内容，导致原本零碎的课程更加零碎。

我不推荐突击学习，不论是大物 XA 还是大物 XB，都需要理解课本定理和推导的过程，在做习题的时候需要理解答案的推导过程。资料中清华题库和上交试题在难度上和哈工大的试卷难度都不相同，如果遇到难度过高的题目不要死磕，难度以课后习题和往年题为参考。
"""

[[advice]]
content = """
突击学习真的很痛苦，但是我两学期都是突击的，甚至大物下突击学习两三周去考试、成绩还算不错——个例仅供参考！

在速通的语境下讨论：按我两个学期的感受，如果你能跟着黎光旭老师的合集学习并理解上课内容，那么对付大计算和大推导大概是没什么问题的，因为**理解定理和习题练手**正是黎老师的上课重点；如果你肯上压力，多花一点时间自己搞懂作业题，拿到高分也完全是有可能的！
"""

[[advice]]
content = """
大学物理 XA 的知识点相对系统，考试相对更侧重对知识点的理解和熟练应用。力学、电磁学需要背诵的地方不多，更多需要的是正确建立物理模型，利用微积分知识解题。题目难的时候还是有一定思维量的，建议有针对性的刷一些题、积累一些技巧。

大学物理 XB 知识点多而散，考试更侧重于对知识点的了解和简单应用，因此也容易考一些比较“偏”的知识点。很多零散的知识点一定要知道其最基本的表述、公式，复习时应力求全面。比如 25 秋的大学物理 XB 考查了速率分布函数意义和费马原理的默写型填空题。

另外，老师还会发本部的阶段训练题供大家练手。阶段训练题的题型和期末考试基本一致，并且考试中也会出现阶段训练题的改编或原题。阶段训练题部分题目比较偏难怪，不必死磕，但整体上还是建议用好这套参考资料的。
"""

[[advice]]
content = """
量子力学不用看网课学，大部分都是高中化学的内容，对于高考选了化学的人来说很好学，只要把 PPT 上的内容理解清楚，公式记牢，再辅以做题可以轻松拿满这部分的分。
"""

[[advice]]
content = """
（针对原 IB 内容/现 XB 内容）
几何光学部分需要重视思路，理解并熟练运用**光程差**是解决所有几何光学问题的关键。
虽然考试是大背诵，但还是需要重视平时课堂上老师对问题分析和推导的过程，能帮助我们打牢数理基础。例如 24 年 IB 期末考试考了薛定谔方程的推导过程，课上老师讲过，但较少人作为复习内容。
需要熟练运用计算器，能够极大提高解题效率。
"""

[[advice]]
content = """
（针对原 IB 内容）
我的对策是多给自己留一些时间用来复习，把物理公式记熟。只要记得住公式和方程，考试时就不会有什么问题。
可以用来练习的成套试卷并不多，因此珍惜每一次练习的机会，反复咀嚼不清楚的地方；清华题库中的题目难度偏高，不建议死磕。
"""
