course_name = "跨专业选修课程体系"
repo_type = "multi-project"
course_code = "CrossSpecialty"

description = """
自 23 级起，跨专业发展课程学分从创新学分 14 分中独立出来，成为单独的 10 学分的跨专业课程学分要求。
跨专业选修课程体系的课程都是非自己本专业的其他专业开设的课程。跨专业课程大体有两类：一类是其他专业的专业课改造而来，如经济学原理；另一类是通识类课程，如普通天文学。
其他专业课改造而来的课程大多有比较丰富的资源，因此单独开一个仓库用于存放相关资料和相关内容要求。
对于跨专业课程，大多数人仅仅是为了修够学校要求的 10 分的跨专业学分，因此，跨专业上课考勤要求和期末考情况是两个很重要的参考因素。以下课程信息主要也集中于这两部分内容。
如果跨专业课程选修的课程在分流后为专业培养方案内的课程，则跨专业课程学分自动成为必修学分/限选学分，而不再作为跨专业学分。
"""

[[courses]]
name = "大学化学III"
code = ""

  [[courses.reviews]]
  topic = "基本信息"
  content = """
  【学分】: 2
  【成绩构成】: 平时作业 60% | 实验 40%
"""
  author = { name = "Maxwell Jay", link = "https://github.com/MaxwellJay256", date = "2023-09" }

  [[courses.reviews]]
  topic = "课程概况"
  content = """
  开课期间要求学生在 3 个模块中各选择一个化学实验完成，每个时长在 3 学时左右。难度整体都一般，还是挺有意思的（在本科期间有多少机会进入化学实验室呢？）。
  大学化学III 没有期末考试，这是这门课对学生最友好的一点，学习压力会小很多。
  总的来说，大学化学III 占用时间精力很少，性价比还是很高的。
"""
  author = { name = "Maxwell Jay", link = "https://github.com/MaxwellJay256", date = "2023-09" }

[[courses]]
name = "生物学导论"
code = ""

  [[courses.reviews]]
  topic = "基本信息"
  content = """
  【学分】: 2
  【成绩构成】: 小测 80% | 课堂汇报 20%
"""
  author = { name = "海边的星空", link = "https://", date = "2025-01" }

  [[courses.reviews]]
  topic = "课程概况"
  content = """
  每个章节讲完后有小测，小测题量较大，使用搜题也要半小时，也有当成作业过。
  只有一次签到且用小测代替。
  课程汇报只要和生物学相关即可，PPT 20 页左右即可。
  给分较宽松，大部分人都有 80+ 甚至 90+
"""
  author = { name = "海边的星空", link = "https://", date = "2025-01" }

[[courses]]
name = "氢能与燃料电池"
code = ""

  [[courses.reviews]]
  topic = "基本信息"
  content = """
  【学分】: 1.5
  【学时构成】: 理论 22 | 实验 2
  【成绩构成】: 作业 40% | 期末考试 60%
"""
  author = { name = "佚名", link = "", date = "" }

  [[courses.reviews]]
  topic = "考查方式更新"
  content = """
  25秋，该课程的课程大纲中增添了闭卷考试，但在实际上课时，仍然遵循无考试，只写一篇小论文的考察方式。
"""
  author = { name = "jiazero", link = "https://github.com/jiazero", date = "2025-12" }

  [[courses.teachers]]
  name = "王夷飞"

    [[courses.teachers.reviews]]
    content = """
    王夷飞老师非常好，允许不去上课，考勤给满分，考核要求是写一篇小论文，给分也很高。
"""
    author = { name = "海边的星空", link = "", date = "2025-01" }

[[courses]]
name = "智慧低碳能源发电技术导论"
code = ""

  [[courses.reviews]]
  topic = "基本信息"
  content = """
  【学分】: 2
  【成绩构成】: 平时成绩 30% | 期末考试 70%
"""
  author = { name = "佚名", link = "", date = "" }

  [[courses.reviews]]
  topic = "考勤与Pre (25秋)"
  content = """
  25 秋共考勤三次，分别为第一节课，汇报那节课和最后一节课。
  增加了一个小组 pre，要求三分钟内讲完，之后小组成员现场回答一个问题，问题很简单，不用担心
"""
  author = { name = "Cecilia", link = "https://github.com/mircecilia/", date = "2026-01" }

  [[courses.teachers]]
  name = "潘泽华"

    [[courses.teachers.reviews]]
    content = """
    潘泽华老师总共考勤两次，上课很简单。老师极善良的。
    考试开卷，可以把上课 PPT 全部打印出来现场找答案，很轻松能拿到接近满分的成绩。
"""
    author = { name = "Caesia-ma", link = "https://github.com/Caesia-ma/", date = "2025-01" }

[[courses]]
name = "水力学"
code = ""

  [[courses.reviews]]
  topic = "基本信息"
  content = """
  【学分】: 2.5
  【学时构成】: 理论学时 32 | 实验学时 8
  【成绩构成】: 作业 30% | 实验 20% | 课堂测验 50%
"""
  author = { name = "佚名", link = "", date = "" }

  [[courses.teachers]]
  name = "刘彤宙"

    [[courses.teachers.reviews]]
    content = """
    刘彤宙老师授课挺好的，但是课本身难度较高,点名和小测会提前通知，小测开卷
"""
    author = { name = "Y-Sensi", link = "https://github.com/Y-Sensi", date = "2025-01" }

[[courses]]
name = "深空探测"
code = ""

  [[courses.reviews]]
  topic = "基本信息"
  content = """
  【学分】: 2
  【成绩构成】: 课堂参与 30% | 期末研讨 30% | 课程论文 40%
"""
  author = { name = "gzz", link = "https://github.com/gzz677", date = "2025-01" }

  [[courses.reviews]]
  topic = "课程概况"
  content = """
  给分很高，上课会提问，没有考试，结课有 pre 和论文。
"""
  author = { name = "gzz", link = "https://github.com/gzz677", date = "2025-01" }

[[courses]]
name = "普通天文学"
code = ""

  [[courses.reviews]]
  topic = "基本信息"
  content = """
  【学分】: 2
  【成绩构成】: 考勤 20% | 作业 30% | 期末考试 60%
"""
  author = { name = "Gaster", link = "https://github.com/WDGaster703", date = "2025-01" }

  [[courses.reviews]]
  topic = "课程概况"
  content = """
  上课考勤4次，共有5次作业。上课会涉及很多很专业的名词和晦涩难懂的概念，也会有很多复杂无比的计算，但是这些都不会要求，本门课程是通识课，只要求最基本的内容。
  期末考试闭卷，可以使用计算器，题型为 10 题填空 + 5 题简答 + 2 题计算。
  有实地观测，地点位于 L8 的小平台。主要使用望远镜观测星空和太阳。
  更多内容可以前往[普通天文学](https://hoa.moe/docs/cross-specialty/spst1004/)中查看。
"""
  author = { name = "Gaster", link = "https://github.com/WDGaster703", date = "2025-01" }

[[courses]]
name = "经济学原理"
code = ""

  [[courses.reviews]]
  topic = "基本信息"
  content = """
  【学分】: 4
  【成绩构成】: 考勤 10% | 作业 15% | 生活中的经济学 15% | 期中考试 30% | 期末考试 30%
"""
  author = { name = "佚名", link = "", date = "" }

  [[courses.reviews]]
  topic = "课程概况"
  content = """
  【学分】: 4
  【成绩构成】: 考勤 10% | 作业 15% | 生活中的经济学 15% | 期中考试 30% | 期末考试 30%

  重量级课程，慎选！
  首先，本门课程上课在周六周日的一、二节，而且持续一学期，这意味着你要上一学期的周末早八。
  其次，上课有非常多的考勤要求，收作业也是老师现场收，不允许补交。期末还有pre。
  其三，本门课有期中考和期末考，虽然 PPT 过一遍后考及格不难，但是如果不想花时间复习的慎选。
  具体的资料可以前往[经济学原理](https://hoa.moe/docs/cross-specialty/econ2005f/)查看。
"""
  author = { name = "佚名", link = "", date = "" }

[[courses]]
name = "OpenHarmony 端云协同物联网开发实践"
code = ""

  [[courses.reviews]]
  topic = "基本信息"
  content = """
  【学分】: 1
  【成绩构成】: 实验报告 60% | 答辩 40%
"""
  author = { name = "离谱", link = "https://github.com/LiPu-jpg", date = "2025-08" }

  [[courses.reviews]]
  topic = "课程概况"
  content = """
  每次上课都考勤，共有5个lab。上课不难，不过会涉及一些稍微专业的概念，不过涉入不深，自己查一下就行了，总体来说由简入深。
  每节课大概率就是教你如何通过各种方式点灯（做拓展有加分，主要就是加一些蜂鸣器放歌，读取温度湿度之类的），大概是从正常的按键到MQTT协议再到接入华为云
  注：这个课在2025夏季第一次开设，所以实际给分情况和教学大纲有区别，基本上你能跟着把每个lab的第一个任务做完就能及格，任务二做完就有80，不强制要求答辩（最后30个同学里就3个上了）拿分还是很简单的
  同时，记得保存实验代码，前四个lab要交代码，第五个还要额外带一份实验报告
  更多内容可以前往[端云协同物联网开发实践-具体lab内容](https://ohiot.p.cs-lab.top/)中查看。
"""
  author = { name = "离谱", link = "https://github.com/LiPu-jpg", date = "2025-08" }

[[courses]]
name = "大模型应用开发入门"
code = ""

  [[courses.teachers]]
  name = "谢佳"

    [[courses.teachers.reviews]]
    content = """
    谢佳老师好说话，上课氛围也比较轻松；知道同学们可能基础薄弱，所以她也欢迎同学提问（会有很多人问问题）。签到是签到表形式。
"""
    author = { name = "IcyDesert", link = "https://github.com/IcyDesert", date = "2025-09" }

  [[courses.reviews]]
  topic = "基本信息"
  content = """
  【学分】: 1
  【成绩构成】: 平时考核 10% | 实验作业 60% | 期末综合项目 30%
"""
  author = { name = "IcyDesert", link = "https://github.com/IcyDesert", date = "2025-09" }

  [[courses.reviews]]
  topic = "课程概况"
  content = """
  推荐有 Python 基础同学选择。这门课依托于 LangChain 等大模型应用库，编写一个实用的大模型应用。注意课程和 **机器学习** 等不同，不涉及底层模型训练；2024 秋课上使用的是通义千问 API。

  有五个小实验，分别对应五个大模型应用开发的知识点，例如大家可能有所耳闻的 RAG、提示词工程等，详见大纲。
  期末结项是综合应用前面的知识点开发一个应用出来；当然老师知道有的同学没有编程基础，所以允许使用 [coze 低代码平台](https://www.coze.cn/) 开发应用。示例项目可参考 [文献阅读助手 - IcyDesert & OverLink](https://github.com/0verL1nk/LLM_App_Final)。
"""
  author = { name = "IcyDesert", link = "https://github.com/IcyDesert", date = "2025-09" }

[[courses]]
name = "城市社会学概论"
code = ""

  [[courses.teachers]]
  name = "周佩玲"

    [[courses.teachers.reviews]]
    content = """
    周佩玲老师很温柔，上课氛围轻松，期中需要参与一次两节连堂的剧本杀，会记录该次出勤，老师还准备了饮料零食。
    考察方式主要是3/4人一组，以小组为单位，期中提交一个计划书，期末将该计划书扩展为PPT并展示。
    无考试，平时上课有时会发腾讯文档，扫码回答一个问题并填写名字，作为考勤方式，但无考勤似乎并不影响通过，周老师善良！
"""
    author = { name = "jiazero", link = "https://github.com/jiazero", date = "2025-12" }

  [[courses.reviews]]
  topic = "基本信息"
  content = """
    【学分】: 1.5
    【成绩构成】: 平时作业 100%
"""
    author = { name = "jiazero", link = "https://github.com/jiazero", date = "2025-12" }

[[courses]]
name = "现代电机设计导论"
code = ""

  [[courses.reviews]]
  topic = "基本信息"
  content = """
  【学分】: 1
  【成绩构成】: 实验报告 50% | 平时分 50%
"""
    author = { name = "jiazero", link = "https://github.com/jiazero", date = "2025-12" }

  [[courses.reviews]]
  topic = "课程概况"
  content = """
  只有一次考勤，考勤方式是纸质名单签字，老师比较善良，无作业，无提问，无考试。
  实验是4学时，我们安排在了周五7,8,9,10节，实际操作7,8节就可以搞定，报告很简单，好课推荐。
"""
  author = { name = "jiazero", link = "https://github.com/jiazero", date = "2025-12" }

[[courses]]
name = "电子封装可靠性"
code = ""

  [[courses.reviews]]
  topic = "基本信息"
  content = """
  【学分】: 2
  【成绩构成】: 课堂表现 20% | 作业报告 40% | 期末考试 40%
"""
  author = { name = "IcyDesert", link = "https://github.com/IcyDesert", date = "2026-01" }

  [[courses.reviews]]
  topic = "课程概况"
  content = """
  大约有 10 次左右的点名考勤，还是比较频繁的；但是老师人很好。

  作业有两个：

  - 给定题目，写一份 7000 字课程论文
  - 自选主题，作大约 8 分钟的课上汇报

  开卷考试，打印资料就能过。
"""
  author = { name = "IcyDesert", link = "https://github.com/IcyDesert", date = "2026-01" }

[[courses]]
name = "机器学习原理与经管应用"
code = ""

  [[courses.reviews]]
  topic = "基本信息"
  content = """
  【学分】: 2
  【成绩构成】: 大作业(实验) 100%
"""
    author = { name = "Gaster", link = "https://github.com/WDGaster703", date = "2025-01" }

  [[courses.teachers]]
  name = "吴璇"

    [[courses.teachers.reviews]]
    content = """
    老师人很好，24秋因为本研上大纲和上课所说不同，老师为我们改了考核要求，改成大作业（即实验）100%，但是25秋恢复了需要论文+课堂汇报+大作业的分数组成了，课堂汇报和论文要求英文写作和表达。

    课程非常非常硬核。虽然名字叫机器学习，但是课程主要内容是经管中的统计问题，涉及大量多元统计学，如多元线性回归等。且PPT几乎是全英文，难以跟上老师上课速度。

    最后的实验难度也颇大，是运用机器学习方法分析某一股票走势或者其他经管问题，对于零基础来说几乎不可能实现。且课堂对此几乎没有涉及。
"""
    author = { name = "Gaster", link = "https://github.com/WDGaster703", date = "2025-01" }

[[courses]]
name = "污染控制微生物学"
code = ""

  [[courses.reviews]]
  topic = "基本信息"
  content = """
    【学分】: 2
    【成绩构成】: 平时 20% | 实验 20% | 课堂汇报 60%
"""
    author = { name = "Gaster", link = "https://github.com/WDGaster703", date = "2025-07" }

  [[courses.teachers]]
  name = "韩炜"

    [[courses.teachers.reviews]]
    content = """
    会有不定时考勤，不过不会凭此挂人。上课不怎么讲知识点，老师会讲一些自己的见解。
    实验共五个，分别是显微镜、革兰氏染色、接种、细菌测数和PCR，实验都很简单，老师很好，而且实验仪器很好玩（PCR分析仪价格可是不菲的）。
    24春有开卷期末考，25春起取消期末考，改为课堂汇报代替。
"""
    author = { name = "Gaster", link = "https://github.com/WDGaster703", date = "2025-07" }

[[courses]]
name = "电动力学"
code = ""

  [[courses.reviews]]
  topic = "基本信息"
  content = """
    【学分】: 3
    【成绩构成】:  平时 30% | 期末考试 70%
"""
    author = { name = "Gaster", link = "https://github.com/WDGaster703", date = "2025-07" }

  [[courses.teachers]]
  name = "秦刚"

    [[courses.teachers.reviews]]
    content = """
    每节课会有遍历点名，但是不会以此挂人。上课颇为硬核，且老师语速慢，吐字比较不清晰，所以很难听懂。
    有四次作业，但是很简单，且此四次作业能决定大部分平时分。
    24春期末考为全选填，25春期末考是五题大题，每道大题都是一个概念的简述，考试内容限于大物电磁学部分，具体可以见资料下载，捞的很狠（最后应该是零人挂科）。
"""
    author = { name = "Gaster", link = "https://github.com/WDGaster703", date = "2025-07" }

[[courses]]
name = "核能与安全"
code = ""

  [[courses.reviews]]
  topic = "基本信息"
  content = """
    【学分】: 1.5
    【成绩构成】: 平时 30% | 课堂汇报 70%
"""
    author = { name = "Gaster", link = "https://github.com/WDGaster703", date = "2026-01" }

  [[courses.teachers]]
  name = "鞠鹏"

    [[courses.teachers.reviews]]
    content = """
    主要内容是核反应与核安全，老师上课不太清晰，且上课节奏很慢。会以低频次的提问代替考勤，不过也不太看重这个。有两次作业，一次是核反应的小计算，一次是核安全的分析思路。
    最后课程报告为核安全事故分析，可以是福岛或者切尔诺贝利或者其他的，汇报无特别具体的要求，三四页word即可。
"""
    author = { name = "Gaster", link = "https://github.com/WDGaster703", date = "2026-01" }

[[courses]]
name = "环境学"
code = ""

  [[courses.reviews]]
  topic = "基本信息"
  content = """
  【学分】: 2
  【成绩构成】: 课堂汇报 30% | 结课论文 70%
"""
  author = { name = "Cecilia", link = "https://github.com/mircecilia/", date = "2025-01" }

  [[courses.reviews]]
  topic = "课程概况"
  content = """
  课堂汇报内容与环境学相关即可，六七个人一组，汇报时间在 15 分钟左右，要求使用英文汇报，老师会用英文提问 ppt 相关内容，要求使用英文回答
  最后结课论文的内容就是你在小组汇报中负责的内容，要求使用英文撰写，长度五到六页左右
"""
  author = { name = "Cecilia", link = "https://github.com/mircecilia/", date = "2025-01" }

[[courses]]
name = "空间环境"
code = ""

  [[courses.reviews]]
  topic = "基本信息"
  content = """
    【学分】: 2
    【成绩构成】: 平时 40% | 期末考试 60%
"""
    author = { name = "IcyDesert", link = "https://github.com/IcyDesert", date = "2025-07" }

  [[courses.teachers]]
  name = "左平兵"

    [[courses.teachers.reviews]]
    content = """
    2025 秋有四次作业，几乎都能在下发的 PPT 找到答案；另外有若干（应该不算分？）的签到表考勤，不过左平兵老师也偶尔点名。结课后会发作业答案。
    考试闭卷，题目和作业有相当部分重合。
"""
    author = { name = "IcyDesert", link = "https://github.com/IcyDesert", date = "2025-07" }

[[courses]]
name = "会计学原理"
code = ""

  [[courses.reviews]]
  topic = "基本信息"
  content = """
    【学分】: 3
    【成绩构成】: 作业 40% | 雨课堂练习 10% | 期末考 50%
"""
    author = { name = "IcyDesert", link = "https://github.com/IcyDesert", date = "2026-01" }


  [[courses.teachers]]
  name = "王世璇"

    [[courses.teachers.reviews]]
    content = """
    首先，本课程所有资料为**全英文**，包括PPT、作业题目、雨课堂练习、**期末试题**；但王世璇老师还是中文讲课。

    - 作业有 8 次，需**英文回答**，交纸质版且不发回 ~~可以丢给 AI 满分完成~~
    - 雨课堂会不定期布置并通知，一般有一周作答；平时无考勤。
    - 期末考试**英文试卷英文作答**，题型分布为选择题30分（3*10=30）+计算分录题（50分，共5题）+简答题（2*10=20）。
      - 计算题把作业搞懂都能做出来
      - 简答题考了「会计周期是什么」和「Financial statement 有哪些」
"""
    author = { name = "IcyDesert", link = "https://github.com/IcyDesert", date = "2026-01" }

[[courses]]
name = "量子力学"
code = ""

  [[courses.reviews]]
  topic = "基本信息"
  content = """
    【学分】: 3
    【成绩构成】: 平时 40% | 期末考试 60%
"""
    author = { name = "Layaka", link = "", date = "2025-12" }


  [[courses.teachers]]
  name = "邓皓键"

    [[courses.teachers.reviews]]
    content = """
    老师很友好，但是普通话有点不好，类似于外国人说中文，但是能听懂。
    上课使用长江雨课堂点名，还会让助教在八点十分左右进行签到。课上不会管你在做什么，但是期末专门认识了几个听课比较认真的同学。
    每节课进行板书，没有 PPT。前面部分和教材基本符合，后面量子计算没有教材，但是难度较低一点。期末考试，听讲＋做好作业很好过。

    2025 年秋季学期考试内容：

    - 第一题，希尔伯特空间相关内容
    - 第二题，波函数相关，归一化和波函数到概率密度
    - 第三题，势垒问题
    - 第四题，势阱问题
    - 第五题，氢原子的物理量nlm
    - 第六题，量子计算，boch球相关
"""
    author = { name = "Layaka", link = "", date = "2025-12" }

[[courses]]
name = "波谱学原理与应用"
code = ""

  [[courses.reviews]]
  topic = "基本信息"
  content = """
    【学分】: 2
    【成绩构成】: 作业 30% | 报告 30% | 期末考试 40%
"""
    author = { name = "lumen", link = "https://github.com/lumen183", date = "2026-01" }


  [[courses.teachers]]
  name = "杨超"

    [[courses.teachers.reviews]]
    content = """
    上课不考勤，偶尔会按点名表顺序抽人回答问题~~在后面的完全不用担心~~，但是习题课一定要去！
    考试难度不大，老师上课很认真很亲切，讲解也很清楚，如果认真听的话一定可以学到东西。
    ppt全英文且课后不发放ppt，期末考看B站的波谱学速成视频就够了。

    - 课程作业每次只有一道题，上交方式为QQ群小程序上交。10min可解决
    - 课程pre在每一小章节结束后的习题课上，形式为微信小程序“OS.波谱学原理与应用”中的对应习题（按点名表序号选题）有半个小时的作答时间，只要讲出分析思路即可（1min左右）~~实测用 AI 完全可以做完~~

    2025 年秋季学期考试内容：

    - 选择题： 20 题，每题 1 分。
    其余为解答题，分布为

    - 谐振子模型估算红外吸收峰
    - 给定结构和紫外吸收波长，判断物质
    - 给定红外吸收峰，判断物质
    - 紫外，红外，质谱仪综合应用。
"""
    author = { name = "lumen", link = "https://github.com/lumen183", date = "2026-01" }

[[courses]]
name = "走进量子世界"
code = ""

  [[courses.reviews]]
  topic = "基本信息"
  content = """
    【学分】: 4
    【成绩构成】: 考试 50% | 课堂汇报 30% | 实验 20%
"""
    author = { name = "潜伏", link = "https://github.com/capoo-fan", date = "2026-01" }


  [[courses.teachers]]
  name = "周宇"

    [[courses.teachers.reviews]]
    content = """
    这一门正如老师自己所说：就是一门福利课。四学分的跨专业课不费吹灰之力。平时有小测和考勤，但是可以不用管，不扣平时分（因为根本就没有）。课堂汇报只要是和量子力学相关的内容基本都是30分/29分。实验可以使用AI，交了实验报告就是20分。最后100分折算成50分的考试也非常容易，老师最后会发两份PDF，只需要对着PDF里面的内容复习即可，掌握量子力学历史、布洛赫球、简单的量子计算就可以轻松过关。四学分美美得吃 :yum:。
"""
    author = { name = "潜伏", link = "https://github.com/capoo-fan", date = "2026-01" }

[[courses]]
name = "公司并购与估值"
code = ""

  [[courses.reviews]]
  topic = "基本信息"
  content = """
    【学分】: 2
    【成绩构成】: 作业 40% | 课堂汇报 60%
"""
    author = { name = "PVZ&X", link = "https://github.com/wpj9362", date = "2026-01" }


  [[courses.teachers]]
  name = "李晶晶"

    [[courses.teachers.reviews]]
    content = """
    虽然是经济管理学院的课，但这门课整体相对友好，难度较低；老师人也非常和善。

    - 考勤略多，形式为课间在黑板上写名字，有时会提前提醒（不是每次都有）。课堂偶尔提问，其他不太管。
    - 有两次需要在课上完成的PPT作业（写一份PPT分析某个具体问题），需要以小组形式完成，每个小组都必须至少选择一次作业进行汇报。不过这非常容易（
    - 期末汇报是案例分析，需要分析一个实际的公司并购案例。汇报时没有提问环节，也是非常轻松。
    - 给分友好，制作PPT只要稍微用心一些就能拿到不低的分数（90+）,对于想提高总学分绩的同学来说是不错的选择。
"""
    author = { name = "PVZ&X", link = "https://github.com/wpj9362", date = "2026-01" }

[[courses]]
name = "绿色金融与碳排放权交易"
code = ""

  [[courses.reviews]]
  topic = "基本信息"
  content = """
    【学分】: 2
    【成绩构成】: 考勤 10% | 论文分析 45% | 课程汇报 45%
"""
    author = { name = "PVZ&X", link = "https://github.com/wpj9362", date = "2026-01" }


  [[courses.teachers]]
  name = "陈小蓓"

    [[courses.teachers.reviews]]
    content = """
    同样是经济管理学院开设的，相对不那么“硬核”的课。

    - 每节课考勤，形式为上课后在名单上签字。不过平时分相对较少，自己取舍吧（）
    - 老师会偶尔“敲打”上课没有听讲的同学、或者提问。课程的内容比较新颖，也有一定价值，感兴趣的同学可以听一听的。
    - 小组作业分为两部分，各占45%。“论文分析”是指阅读一篇绿色金融有关题材的论文，然后在课上作报告，谈谈你对论文的理解；“课堂汇报”则是需要自己根据所学内容，撰写绿色金融与碳排放权交易有关的案例分析，然后在课上汇报。老师会把上课的PPT和往届学生的汇报案例发到群里，供大家参考写作格式和内容。
    这门课每节课考勤，给分不算高但肯定能过（本人是84，排名24/60）且小组作业的工作量不少，也比较新颖。因此建议在小组组好队后，尽快明确职责，分配好各自负责的部分（论文搜集与写作、PPT制作、汇报），这样可以省不少心。不过介于这门课不设置考试的属性，意味着你只要把该做的工作做完，就能轻松获得2学分。
"""
    author = { name = "PVZ&X", link = "https://github.com/wpj9362", date = "2026-01" }

[[courses]]
name = "数智结构概论"
code = ""

  [[courses.reviews]]
  topic = "基本信息"
  content = """
    【学分】: 3
    【成绩构成】: 考勤 40% | 作业 60%
"""
    author = { name = "SpeechlessPanda", link = "https://github.com/SpeechlessPanda", date = "2026-01" }


  [[courses.teachers]]
  name = "蔡坤"

    [[courses.teachers.reviews]]
    content = """

    - 每节课考勤，形式为课前扫码签到。按理来说可以签完到就溜，但是老师后面会有抽签提问环节，要是抽到了不在那节课考勤就算不在。
    - 课程形式是上半节讲内容，下半节看视频，然后最后几分钟会根据视频内容提问。每节课都有课后作业，下星期的那天交，内容也是跟视频内容相关，大家大部分都是用电脑写好打印出来提交（因为真的很多）。
    - 给分比较宽松，考勤和作业没问题的话都能过，我是A，不过好像作业有一定次数没交老师就会让助教挂你的科。
    - 是一个有点保守的老师，用他自己的话来说也有点说什么比较不顾忌。上课时要注意保持本心，培养辩证思维能力（doge）。
    - 因为种种原因（老师体验感不太好），这门课貌似已成为绝版课程，个人觉得挺可惜，毕竟三分好水的跨专业也不多。
"""
    author = { name = "SpeechlessPanda", link = "https://github.com/SpeechlessPanda", date = "2026-01" }

[[courses]]
name = "软体机器人理论与技术"
code = ""

  [[courses.reviews]]
  topic = "基本信息"
  content = """
    【学分】: 2
    【成绩构成】: 作业和随堂测试 40% | 期末报告 60%
"""
    author = { name = "SpeechlessPanda", link = "https://github.com/SpeechlessPanda", date = "2026-01" }


  [[courses.teachers]]
  name = "郭江龙/周健友"

    [[courses.teachers.reviews]]
    content = """
    - 理论上没有考勤，但是据老师说上次教评的时候有专家问课程考勤率是怎么得到的，导致老师后面开始考勤。周老师的形式是抽人回答问题，一般按花名册顺序，每个人都会被抽到一次，抽到没来的后面会再抽一次，那一次来了应该问题就不大。郭老师则是用随堂测试的形式来记录考勤。
    - 随堂测试比较简单，略过不讲。小作业的话，郭老师的比较好弄，交给ai然后给py代码画个图写个过程就行。周老师的小作业就是简化版的期末报告，比较麻烦，不过我们这一届的截止日期是在期末考试之后，而且一两个小时多半都能搞定，所以还算可以。期末报告同理，也是一两个小时就能搞定（这只是按我的经验来说，群里好像有些同学弄这个弄了很久）。
    - 期末报告我没理解错的话应该是叫你类似于总结已经有了的东西，然后图片也是找网上现有的。有些同学弄得慢好像是在自己画图（？）。
    - 软体机器人作为一个前沿方向还是非常大有可为，如果以后想在这方面有所发展的可以选这门课，跟两个老师搭上关系。两个老师讲的也很不错，属于是想听课的同学也能听下去的那种。
    - 一开始说这门课给分比较低，但是我作为一个两三个小时完成大小作业加考勤没缺过的人来说，分数还是挺高的好像，比我不少考试课分数都高（悲），所以非常推荐选，最好能和舍友一起，这样考勤问题也能大大解决。
"""
    author = { name = "SpeechlessPanda", link = "https://github.com/SpeechlessPanda", date = "2026-01" }

[[courses]]
name = "行星科学"
code = ""

  [[courses.reviews]]
  topic = "基本信息"
  content = """
    【学分】: 2
    【成绩构成】: 课堂汇报 50% | 课程论文 50%
"""
    author = { name = "潜伏", link = "https://github.com/capoo-fan", date = "2026-01" }

  [[courses.teachers]]
  name = "张铁龙/肖苏东"

    [[courses.teachers.reviews]]
    content = """
    期中一次pre，期末一次pre，最后交个论文就行，说是最简单的跨专业课也不为过。平时有一两次点名，但是不会影响及格。唯一的缺点是课程容量只有30人，抢课时代还有机会可以抢到，现在变成抽签就听天由命了。
"""
    author = { name = "潜伏", link = "https://github.com/capoo-fan", date = "2026-01" }

[[courses]]
name = "基础计量经济学"
code = ""

  [[courses.reviews]]
  topic = "基本信息"
  content = """
    【学分】: 3
    【成绩构成】: 平时作业 40% | 期末考试 50% | 课堂表现 10%
"""
    author = { name = "fruly-ZERO", link = "https://github.com/fruly-ZERO", date = "2026-01" }

  [[courses.teachers]]
  name = "赵柘锦"

    [[courses.teachers.reviews]]
    content = """
    - 慎重选择， 48 学时，内容比较多而且很偏统计学，并且还有配套的实验课，主要是学会使用 stata 分析和处理数据，需要在课后提交实验报告。
    - 考勤方面，不是非常严格，只有一两次考勤，不过课堂表现打分仿佛并不是完全依据考勤给的。
    - 作业方面，老师建议使用 latex，题目不难，一共要交四次，但是记得要及时交。
    - 课堂教学方面，感觉需要比较好的统计学基础，内容还是比较硬核的，并不是非常简单易懂，但老师有时候会讲一些小故事和现实案例什么的挺好玩的，还会和同学偶尔互动下。老师人比较年轻，比较友好。如果确实想学到知识还是可以好好听一下。
    - 实验课是由实验中心的王婷老师负责，先讲 ppt 再在 ppt 上留作业，即完成一份实验报告，内容量不少，需要在 stata 上写代码，相当于学一门新的语言了。老师很温柔，不会的地方可以举手问她。实验课每节课都要签到。
    - 考试方面，不考实验课涉及的部分，只考理论课的内容。不复习的话考试基本上是没法考的，但是老师的 ppt 又特别特别多，如果选了这门课的同学还是建议至少预留两三天时间复习期末考（虽然应该也不太容易挂科，毕竟考试只占百分之五十）。
"""
    author = { name = "fruly-ZERO", link = "https://github.com/fruly-ZERO", date = "2026-01" }
